### ISSUE TITLE
Can not install sysv_ipc from pypi.python.org

### ISSUE THREAD

**Issue by vss888** [osvenskan/sysv_ipc#6]
This is what I get when I try to install it using pip:

> ~ $ pip3 install --trusted-host pypi.python.org sysv_ipc
> Collecting sysv_ipc
>   Using cached https://files.pythonhosted.org/packages/08/7d/a862f3045fa191eeece23650725273f2ccaf9ac6b95443dfe4cac6508638/sysv_ipc-1.0.0.tar.gz
>     Complete output from command python setup.py egg_info:
>     Traceback (most recent call last):
>       File "<string>", line 1, in <module>
>       File "/tmp/pip-install-qk2fl7fr/sysv-ipc/setup.py", line 41, in <module>
>         prober.probe()
>       File "/tmp/pip-install-qk2fl7fr/sysv-ipc/prober.py", line 137, in probe
>         d["PAGE_SIZE"] = probe_page_size()
>       File "/tmp/pip-install-qk2fl7fr/sysv-ipc/prober.py", line 111, in probe_page_size
>         page_size = compile_and_run("probe_page_size.c")
>       File "/tmp/pip-install-qk2fl7fr/sysv-ipc/prober.py", line 83, in compile_and_run
>         stdout=subprocess.PIPE).communicate()[0]
>       File ".../Python-3.6.3/lib/python3.6/subprocess.py", line 709, in __init__
>         restore_signals, start_new_session)
>       File ".../Python-3.6.3/lib/python3.6/subprocess.py", line 1344, in _execute_child
>         raise child_exception_type(errno_num, err_msg, err_filename)
>     PermissionError: [Errno 13] Permission denied: './prober/foo'
>     
>     ----------------------------------------
> Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-qk2fl7fr/sysv-ipc/

Please, let me know what I might be doing wrong.
Thank you!

**Comment by vss888** [comment]
Installing from the tar.gz file gives:

> sysv_ipc-1.0.0 $ python setup.py install
> running install
> error: can't create or remove files in install directory
> 
> The following error occurred while trying to add or remove files in the
> installation directory:
> 
>     [Errno 13] Permission denied: '/usr/lib64/python2.7/site-packages/test-easy-install-64483.write-test'
> 
> The installation directory you specified (via --install-dir, --prefix, or
> the distutils default setting) was:
> 
>     /usr/lib64/python2.7/site-packages/
> 
> Perhaps your account does not have write access to this directory?  If the
> installation directory is a system-owned directory, you may need to sign in
> as the administrator or "root" account.  If you do not have administrative
> access to this machine, you may wish to choose a different installation
> directory, preferably one that is listed in your PYTHONPATH environment
> variable.
> 
> For information on other options, you may wish to consult the
> documentation at:
> 
>   https://pythonhosted.org/setuptools/easy_install.html
> 
> Please make the appropriate changes for your system and try again.

I think the setup.py script ignores the Python-3 version which I compiled myself from source in ~/bin and instead attempts to install in the system default Python-2 directory.

**Comment by vss888** [comment]
Running 

> sysv_ipc-1.0.0 $ python3 setup.py install

allows to install sysv_ipc successfully.
